# Generated by Django 5.0.7 on 2024-07-11 12:00

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horijiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Loyiha nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Jarayonda'), ('deactive', 'Tugatilgan')], max_length=100, verbose_name='Holati')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('update', models.DateTimeField(auto_now=True, verbose_name="O'zagrtirilgan")),
                ('masul_vakil', models.CharField(choices=[('A.Abdurazakov', 'Sh.Abdurazzaqov'), ('A.Abduhakimov', 'A.Abduhakimov'), ('O.Inamov', 'O.Inamov')], max_length=250)),
                ('tuman', models.CharField(choices=[('namangan_shahar', 'Namangan shahar'), ('mingbuloq', 'Mingbuloq'), ('chust', 'Chust'), ('norin', 'Norin'), ('pop', 'Pop')], max_length=100)),
                ('loyiha_quvvati', models.CharField(max_length=250)),
                ('boshlash_sanasi', models.DateField(default='2024-01-01', verbose_name='Boshlash')),
                ('tugatish_sanasi', models.DateField(default='2024-01-01', verbose_name='Tugatish')),
                ('davlat', models.CharField(max_length=250)),
                ('soha_yonalishi', models.CharField(choices=[('xizmat', 'Xizmat'), ('sanoat', 'Sanoat'), ('qishloq', 'Qishloq')], max_length=100)),
                ('loyiha_qiymati', models.CharField(max_length=250)),
                ('pdf_file', models.FileField(upload_to='pdf/%Y/', verbose_name='Tasdiqlangani')),
                ('excel_file', models.FileField(upload_to='excel/%Y/', verbose_name='Tarmoq jadvali')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
