# Generated by Django 5.0.7 on 2024-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horijiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horijiy',
            name='loyiha_qiymati',
            field=models.IntegerField(default=0),
        ),
    ]
