# Generated by Django 5.0.7 on 2024-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horijiy', '0002_alter_horijiy_loyiha_qiymati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horijiy',
            name='soha_yonalishi',
            field=models.CharField(choices=[('Xizmat', 'Xizmat'), ('Sanoat', 'Sanoat'), ('Qishloq', 'Qishloq')], max_length=100),
        ),
        migrations.AlterField(
            model_name='horijiy',
            name='tuman',
            field=models.CharField(choices=[('Namangan_shahar', 'Namangan shahar'), ('Davlatobod', 'Davlatobod'), ('Yangi Namangan', 'Yangi Namangan'), ('Mingbuloq', 'Mingbuloq'), ('Kosonsoy', 'Kosonsoy'), ('Namangan', 'Namangan'), ('Norin', 'Norin'), ('Pop', 'Pop'), ('To`raqo`rg`on', 'To`raqo`rg`on'), ('Uychi', 'Uychi'), ('Uchqo`rg`on', 'Uchqo`rg`on'), ('Chortoq', 'Chortoq'), ('Chust', 'Chust'), ('Yangiqo`rg`on', 'Yangiqo`rg`on')], max_length=100),
        ),
    ]
