# Generated by Django 5.0.7 on 2024-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horijiy', '0003_alter_horijiy_soha_yonalishi_alter_horijiy_tuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horijiy',
            name='status',
            field=models.CharField(choices=[('active', 'Jarayonda'), ('deactive', 'Tugatilgan'), ('expired', 'Muddati o`tgan')], max_length=100, verbose_name='Holati'),
        ),
    ]
